"use client";

import { useState } from "react";
import { MessageSquare, Loader2, Sparkles } from "lucide-react";

interface DiscussionThreadsProps {
    title: string;
    description: string;
    reflections?: string[];
}

export default function DiscussionThreads({ title, description, reflections }: DiscussionThreadsProps) {
    const [questions, setQuestions] = useState<string[]>([]);
    const [isLoading, setIsLoading] = useState(false);
    const [hasAttempted, setHasAttempted] = useState(false);

    const generateQuestions = async () => {
        setIsLoading(true);
        setHasAttempted(true);

        try {
            const res = await fetch("/api/generate-discussion", {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({ title, description, reflections }),
            });

            if (!res.ok) throw new Error("Failed to generate");

            const data = await res.json();
            if (data.questions) setQuestions(data.questions);

        } catch (error) {
            console.error(error);
        } finally {
            setIsLoading(false);
        }
    };

    if (questions.length === 0 && !hasAttempted) {
        return (
            <div className="mt-8 p-6 bg-amber-50 rounded-2xl border border-amber-100/50">
                <div className="flex items-start gap-4">
                    <div className="p-3 bg-amber-100 text-amber-600 rounded-full">
                        <Sparkles size={20} />
                    </div>
                    <div>
                        <h4 className="font-bold text-amber-900 mb-1">Deepen the Process</h4>
                        <p className="text-amber-700/80 text-sm mb-4">
                            Generate thoughtful, process-oriented discussion questions based on this entry to spark meaningful peer feedback.
                        </p>
                        <button
                            onClick={generateQuestions}
                            className="text-sm px-4 py-2 bg-amber-500 hover:bg-amber-600 text-white font-bold rounded-lg transition-colors"
                        >
                            Generate Prompts
                        </button>
                    </div>
                </div>
            </div>
        );
    }

    if (isLoading) {
        return (
            <div className="mt-8 p-6 bg-slate-50 flex items-center justify-center rounded-2xl border border-slate-100">
                <Loader2 className="animate-spin text-amber-500 mr-2" />
                <span className="text-slate-500 font-medium">Generating process questions...</span>
            </div>
        )
    }

    if (questions.length === 0 && hasAttempted) {
        return null;
    }

    return (
        <div className="mt-8">
            <h3 className="text-lg font-bold text-slate-800 flex items-center gap-2 mb-4">
                <MessageSquare size={18} className="text-amber-500" />
                Process Prompts
            </h3>
            <div className="space-y-3">
                {questions.map((q, idx) => (
                    <div key={idx} className="p-4 bg-white border border-slate-200 rounded-xl shadow-sm text-slate-700 font-medium leading-relaxed">
                        {q}
                    </div>
                ))}
            </div>
            <p className="text-xs text-slate-400 mt-3 text-center">Generated by Process+ AI to encourage deep reflection.</p>
        </div>
    );
}
